<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 12.04.19
 * Time: 12:55
 */

namespace app\modules\history\front\controllers;


use app\modules\history\models\Chapters;
use app\modules\history\models\Subchapters;
use mtemplate\mcontrollers\MBTController;
use yii\data\Pagination;
use yii\web\NotFoundHttpException;

class DefaultController extends MBTController
{
    public function beforeAction($action)
    {
        $this->layout = '//front/content';

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $query = Chapters::find()->active();

        if (!$query->exists()) {
            throw new NotFoundHttpException();
        }

        $countQuery = clone $query;

        $count = $countQuery->count();

        $pagination = new Pagination(['totalCount' => $count, 'defaultPageSize' => 2, 'forcePageParam' => false]);

        $models = $query->limit($pagination->limit)->offset($pagination->offset)->orderBy(['created_at' => SORT_ASC])->all();

        $this->setMeta(\Yii::t('front', 'Исторический очерк'));

        return $this->render('index', ['models' => $models, 'pagination' => $pagination]);
    }

    public function actionView($id)
    {
        $model = Subchapters::findOne(['id' => $id]);

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        $this->setMeta($model->meta_title ? $model->meta_title : $model->title,
            $model->meta_description ? $model->meta_description : $model->sub_title,
            $model->meta_keywords);

        return $this->render('view', ['model' => $model]);
    }
}